version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: submodules
          command: git submodule update --init --recursive
      - run:
          name: apt
          command: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y gcc-riscv64-linux-gnu python3-venv
      - run:
          name: check
          command: make check
workflows:
  smoke:
    jobs:
      - build
